import "./globals.css";
import "./fonts.css";

import Footer from "./_components/Footer";
import Nav from "./_components/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased md:pt-[30px] pt-[14px]  w-full`}
        style={{ fontFamily: "var(--font-sf-pro-display)" }}
      >
        <div className="md:px-[45px] px-[25px]">
          <Nav />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
