import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./fonts.css";
import Nav from "./_components/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased md:py-[30px] py-[14px] md:px-[45px] px-[25px] w-full`}
        style={{ fontFamily: "var(--font-sf-pro-display)" }}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
